#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import csv

# Datos completos para challenge_options_leccion2.csv
options_data = [
    ["id", "challenge_id", "text", "correct", "image_src", "audio_src"],
    [109, 37, "Graves y leves.", "false", "", ""],
    [110, 37, "Intencionales o de imprudencia.", "true", "", ""],
    [111, 37, "Dolosos y culposos.", "false", "", ""],
    [112, 37, "Consumados e intentados.", "false", "", ""],
    [113, 38, "Que se cometa por negligencia o inobservancia de un deber.", "false", "", ""],
    [114, 38, "Que se ejecute por una orden superior jerárquica.", "false", "", ""],
    [115, 38, "Que se cometa con el ánimo de producir el resultado que las leyes castigan.", "true", "", ""],
    [116, 38, "Que se produzca un resultado material sin que el activo lo deseara.", "false", "", ""],
    [117, 39, "La intención manifiesta de dañar a un tercero.", "false", "", ""],
    [118, 39, "Falta de cautela, negligencia o ignorancia o inobservancia de un deber.", "true", "", ""],
    [119, 39, "El intento de ocultar a otro responsable.", "false", "", ""],
    [120, 39, "La inducción a un tercero para que cometa el delito.", "false", "", ""],
    [121, 40, "Los cómplices.", "false", "", ""],
    [122, 40, "Los autores.", "false", "", ""],
    [123, 40, "Los peritos.", "true", "", ""],
    [124, 40, "Los encubridores.", "false", "", ""],
    [125, 41, "Los que auxilian al autor en los preparativos del delito.", "false", "", ""],
    [126, 41, "Los que en unión de otros toman parte en la ejecución.", "false", "", ""],
    [127, 41, "Los que conciben, preparan, ejecutan, dirigen la ejecución, o fuerzan/inducen a otros a cometerlo.", "true", "", ""],
    [128, 41, "Los que ocultan al responsable sin proponerse lucro.", "false", "", ""],
    [129, 42, "Los que asumen la dirección y control de la ejecución del delito.", "false", "", ""],
    [130, 42, "Los que en unión de otros, y de común acuerdo, toman parte en la ejecución.", "true", "", ""],
    [131, 42, "Los que proporcionan los instrumentos necesarios para el crimen.", "false", "", ""],
    [132, 42, "Los que conciben el delito pero no participan en la ejecución.", "false", "", ""],
    [133, 43, "Ejecutan el delito por sí mismos.", "false", "", ""],
    [134, 43, "Fuerzan o inducen a otros a cometer el delito.", "false", "", ""],
    [135, 43, "Auxilian al autor o autores en los preparativos o lo facilitan por actos simultáneos o posteriores a la ejecución.", "true", "", ""],
    [136, 43, "Ocultan los instrumentos del delito a la autoridad.", "false", "", ""],
    [137, 44, "Que se haga bajo la promesa de un pago o recompensa.", "false", "", ""],
    [138, 44, "Que el responsable sea un superior jerárquico.", "false", "", ""],
    [139, 44, "Que no se propongan interés o lucro al auxiliar al delincuente.", "true", "", ""],
    [140, 44, "Que se utilicen medios violentos para ocultar al delincuente.", "false", "", ""],
    [141, 45, "Prisión, multa y suspensión de derechos políticos.", "false", "", ""],
    [142, 45, "Prisión, destierro, sujeción a vigilancia de la policía y multa.", "true", "", ""],
    [143, 45, "Reclusión, destierro, degradación y amonestación.", "false", "", ""],
    [144, 45, "Arresto, destitución de empleo y sujeción a vigilancia de la policía.", "false", "", ""],
    [145, 46, "En el Cuartel General de la zona militar correspondiente al reo.", "false", "", ""],
    [146, 46, "En cualquier penal militar que determine la Secretaría de la Defensa Nacional.", "false", "", ""],
    [147, 46, "En las prisiones militares.", "true", "", ""],
    [148, 46, "En los establecimientos de reclusión civil más cercanos al lugar donde se cometió el delito.", "false", "", ""],
    [149, 47, "La prohibición de residir en cualquier instalación militar.", "false", "", ""],
    [150, 47, "La pérdida definitiva de todos los grados y honores militares.", "false", "", ""],
    [151, 47, "La prohibición de habitar un lugar del territorio nacional que no exceda de 50 kilómetros.", "false", "", ""],
    [152, 47, "La prohibición de residir en un lugar determinado que no exceda de 50 kilómetros del domicilio del penado.", "true", "", ""],
    [153, 48, "No podrá exceder de cinco años.", "false", "", ""],
    [154, 48, "Es una pena exclusivamente impuesta a los oficiales.", "false", "", ""],
    [155, 48, "No podrá exceder de cinco años y se limita a una inspección que impida al reo ser jefe de banda o asociación, sin ser ofensiva a la honra.", "true", "", ""],
    [156, 48, "Implica que el reo no puede abandonar su domicilio por más de 72 horas.", "false", "", ""],
    [157, 49, "Siempre se fija en una cantidad determinada para todos los delitos militares.", "false", "", ""],
    [158, 49, "Consiste en la obligación de pagar un salario mínimo diario por cada día de prisión.", "false", "", ""],
    [159, 49, "Consiste en la obligación de pagar una cantidad determinada que la ley señala.", "true", "", ""],
    [160, 49, "El juez la establece según su criterio, sin límite mínimo o máximo.", "false", "", ""],
    [161, 50, "Siempre debe sustituirse por el destierro.", "false", "", ""],
    [162, 50, "Podrá conmutarse a juicio del tribunal por Destierro o Sujeción a vigilancia de la policía.", "true", "", ""],
    [163, 50, "Se sustituye obligatoriamente por una multa equivalente.", "false", "", ""],
    [164, 50, "Se impondrá la pena de Amonestación en lugar de prisión.", "false", "", ""],
    [165, 51, "Son penas principales impuestas por todos los delitos graves.", "false", "", ""],
    [166, 51, "Son penas que siempre se imponen como consecuencia de la sentencia condenatoria.", "true", "", ""],
    [167, 51, "Únicamente se aplican a los subalternos.", "false", "", ""],
    [168, 51, "Nunca se aplican a los reos que cumplen condena en prisiones civiles.", "false", "", ""],
    [169, 52, "Se niegue a cumplir una orden de su superior jerárquico por razones de conciencia.", "true", "", ""],
    [170, 52, "Tome las armas en contra de la Nación.", "false", "", ""],
    [171, 52, "Sirva en el ejército enemigo o se una a sus fuerzas.", "false", "", ""],
    [172, 52, "Procure la evasión de prisioneros de guerra que pertenezcan al ejército enemigo.", "false", "", ""],
    [173, 53, "Prisión de veinte a sesenta años.", "false", "", ""],
    [174, 53, "Prisión de treinta a sesenta años.", "true", "", ""],
    [175, 53, "Destitución del empleo y prisión por quince años.", "false", "", ""],
    [176, 53, "Destierro y multa.", "false", "", ""],
    [177, 54, "Buscar refugio político en territorio nacional.", "false", "", ""],
    [178, 54, "Obtener informes relativos a la defensa de la Nación.", "true", "", ""],
    [179, 54, "Sustraer víveres o pertrechos de guerra.", "false", "", ""],
    [180, 54, "Entregar comunicaciones personales a militares de alto rango.", "false", "", ""],
    [181, 55, "Prisión de seis a quince años.", "false", "", ""],
    [182, 55, "Prisión de diez a veinticinco años.", "false", "", ""],
    [183, 55, "Prisión de quince a treinta años.", "true", "", ""],
    [184, 55, "Destitución del empleo y prisión de un año.", "false", "", ""],
    [185, 56, "El uso de información confidencial para obtener un ascenso.", "false", "", ""],
    [186, 56, "La revelación de secretos de guerra o de la defensa nacional que pueda dañar a la Nación.", "true", "", ""],
    [187, 56, "La publicación de un libro sobre historia militar sin autorización previa.", "false", "", ""],
    [188, 56, "La comunicación de datos estadísticos sobre el personal a la prensa.", "false", "", ""],
    [189, 57, "Destitución de empleo e inhabilitación.", "false", "", ""],
    [190, 57, "Prisión de diez a veinte años.", "true", "", ""],
    [191, 57, "Prisión de cinco a diez años si es en tiempo de paz.", "false", "", ""],
    [192, 57, "Multa y sujeción a vigilancia de la policía.", "false", "", ""],
    [193, 58, "La pena de prisión señalada en el Artículo 202.", "false", "", ""],
    [194, 58, "Destitución del empleo y arresto.", "false", "", ""],
    [195, 58, "Prisión de uno a cinco años.", "true", "", ""],
    [196, 58, "Amonestación y suspensión temporal del empleo.", "false", "", ""],
    [197, 59, "Logra un ascenso en el ejército.", "false", "", ""],
    [198, 59, "Causare daño a la Nación.", "true", "", ""],
    [199, 59, "Firma un acuerdo de cooperación técnica.", "false", "", ""],
    [200, 59, "Se reúne con el comandante enemigo sin testigos.", "false", "", ""],
    [201, 60, "Prisión de seis meses a dos años.", "false", "", ""],
    [202, 60, "Prisión de cinco a veinte años.", "true", "", ""],
    [203, 60, "Degradación y destitución del empleo.", "false", "", ""],
    [204, 60, "La misma pena que la traición a la Patria.", "false", "", ""],
    [205, 61, "Para asistir a una emergencia familiar.", "false", "", ""],
    [206, 61, "Para pasarse a las filas enemigas.", "true", "", ""],
    [207, 61, "Por enfermedad repentina.", "false", "", ""],
    [208, 61, "Para auxiliar a un compañero herido en combate.", "false", "", ""],
    [209, 62, "Prisión de dos a diez años.", "false", "", ""],
    [210, 62, "Prisión de diez a veinte años.", "true", "", ""],
    [211, 62, "Destitución del empleo y arresto.", "false", "", ""],
    [212, 62, "La misma pena que el espionaje en tiempo de paz.", "false", "", ""],
    [213, 63, "Destitución e inhabilitación del servicio.", "false", "", ""],
    [214, 63, "Prisión de quince a treinta años.", "true", "", ""],
    [215, 63, "Arresto y sujeción a vigilancia de la policía.", "false", "", ""],
    [216, 63, "La pena de traición en tiempo de guerra.", "false", "", ""],
    [217, 64, "Desobedecen las órdenes de un superior jerárquico.", "false", "", ""],
    [218, 64, "Promueven la deserción de las tropas en tiempo de paz.", "false", "", ""],
    [219, 64, "Se alcen en armas contra el Gobierno de la Unión, o lo inciten a hacerlo.", "true", "", ""],
    [220, 64, "Se nieguen a acudir a un llamado de concentración en caso de emergencia.", "false", "", ""],
    [221, 65, "Prisión de uno a diez años.", "false", "", ""],
    [222, 65, "Prisión de cinco a veinte años.", "true", "", ""],
    [223, 65, "Arresto y destitución del empleo.", "false", "", ""],
    [224, 65, "Degradación y sujeción a vigilancia de la policía.", "false", "", ""],
    [225, 66, "Duplicará, por haber actuado sin control.", "false", "", ""],
    [226, 66, "Reducirá a la cuarta parte de la pena que corresponda.", "true", "", ""],
    [227, 66, "Mantendrá igual, pero se conmutará por una multa.", "false", "", ""],
    [228, 66, "Anulará totalmente, al considerarse arrepentimiento.", "false", "", ""],
    [229, 67, "Que la rebelión se haya consumado, pero sin causar daños mayores a tres millones de pesos.", "false", "", ""],
    [230, 67, "Que la rebelión sea iniciada únicamente por personal de tropa, sin participación de oficiales.", "false", "", ""],
    [231, 67, "Que el delincuente se separe de la rebelión antes de que esta cause daño o derramamiento de sangre.", "true", "", ""],
    [232, 67, "Que el delincuente no haya tenido conocimiento de la gravedad de su acción.", "false", "", ""],
    [233, 68, "Los rebeldes utilizaron armas cortas de fuego.", "false", "", ""],
    [234, 68, "Los rebeldes se rinden antes de 48 horas.", "false", "", ""],
    [235, 68, "El militar tiene el mando superior de las tropas o es el promotor principal de la rebelión.", "true", "", ""],
    [236, 68, "La rebelión ocurre en tiempo de paz y sin causar estragos.", "false", "", ""],
    [237, 69, "Contra el Congreso de la Unión.", "false", "", ""],
    [238, 69, "Contra el Comandante Supremo de las Fuerzas Armadas.", "false", "", ""],
    [239, 69, "Contra las órdenes de un superior, o los que se reúnan en grupo para hacer alguna reclamación, con amenaza o fuerza.", "true", "", ""],
    [240, 69, "Contra la autoridad judicial militar o civil.", "false", "", ""],
    [241, 70, "Arresto de tres días y destitución del empleo.", "false", "", ""],
    [242, 70, "Prisión de seis meses a cinco años.", "false", "", ""],
    [243, 70, "Prisión de uno a diez años.", "true", "", ""],
    [244, 70, "Degradación y sujeción a vigilancia de la policía.", "false", "", ""],
    [245, 71, "Todos los individuos de tropa que participaron.", "false", "", ""],
    [246, 71, "Únicamente los que ejecutaron actos de violencia.", "false", "", ""],
    [247, 71, "Los que hubieren tenido el mando de la tropa o los que la hubieren promovido o dirigido.", "true", "", ""],
    [248, 71, "Los que, siendo oficiales, no la hayan denunciado.", "false", "", ""],
    [249, 72, "Se entrega a las autoridades civiles antes de ser detenido.", "false", "", ""],
    [250, 72, "Se retracta y abandona la sedición en cualquier momento.", "false", "", ""],
    [251, 72, "Se separa de la sedición antes de que haya causado daño o derramamiento de sangre y sin que haya sido descubierto.", "true", "", ""],
    [252, 72, "Entrega a las autoridades al promotor principal del movimiento.", "false", "", ""],
    [253, 73, "Abandona su puesto de centinela sin causa justificada.", "false", "", ""],
    [254, 73, "Promueve la rebelión o sedición en su unidad.", "false", "", ""],
    [255, 73, "Con palabras, gestos, actitudes, escritos o de cualquier modo, falte al respeto o a la obediencia debida a un superior.", "true", "", ""],
    [256, 73, "Se niega a entregar su armamento de cargo al serle solicitado.", "false", "", ""],
    [257, 74, "Prisión de seis meses a cinco años.", "false", "", ""],
    [258, 74, "Prisión de uno a dos años.", "true", "", ""],
    [259, 74, "Arresto y destitución del empleo.", "false", "", ""],
    [260, 74, "Destierro y multa.", "false", "", ""],
    [261, 75, "Comete el delito frente a sus subalternos.", "false", "", ""],
    [262, 75, "Emplea la fuerza o la amenaza contra el superior.", "true", "", ""],
    [263, 75, "Se encuentra en tiempo de guerra o campaña.", "false", "", ""],
    [264, 75, "Es reincidente en el delito de desobediencia.", "false", "", ""],
    [265, 76, "Prisión de diez a veinte años.", "false", "", ""],
    [266, 76, "Prisión de tres a seis años.", "false", "", ""],
    [267, 76, "Prisión de cinco a veinte años.", "true", "", ""],
    [268, 76, "Destitución de empleo y degradación.", "false", "", ""],
    [269, 77, "Prisión de tres meses a dos años.", "false", "", ""],
    [270, 77, "Prisión de uno a dos años.", "true", "", ""],
    [271, 77, "Arresto y multa.", "false", "", ""],
    [272, 77, "Suspensión temporal del cargo y destierro.", "false", "", ""],
    [273, 78, "Realiza el acto arbitrario fuera de las instalaciones militares.", "false", "", ""],
    [274, 78, "Obliga al inferior a cometer un delito, aunque este no se consumase.", "true", "", ""],
    [275, 78, "Maltrata a un inferior que es oficial o suboficial.", "false", "", ""],
    [276, 78, "Abusa de su autoridad en presencia de civiles.", "false", "", ""],
    [277, 79, "Se reducirá a la mitad.", "false", "", ""],
    [278, 79, "Se sumará de forma íntegra.", "false", "", ""],
    [279, 79, "Se conmutará por una multa.", "false", "", ""],
    [280, 79, "Se aumentará de un tercio a la mitad.", "true", "", ""],
    [281, 80, "Destitución del empleo y arresto.", "false", "", ""],
    [282, 80, "Prisión de seis meses a un año.", "false", "", ""],
    [283, 80, "Prisión de uno a tres años.", "true", "", ""],
    [284, 80, "Prisión de dos a cinco años.", "false", "", ""],
    [285, 81, "Se niega a cumplir una orden que considera injusta.", "false", "", ""],
    [286, 81, "Se insubordina verbalmente en presencia de subalternos.", "false", "", ""],
    [287, 81, "Se resista a obedecer una orden de su superior en cualquier acto del servicio.", "true", "", ""],
    [288, 81, "No asiste a un pase de revista sin causa justificada.", "false", "", ""],
    [289, 82, "Arresto mayor y sujeción a vigilancia.", "false", "", ""],
    [290, 82, "Prisión de dos meses a un año.", "true", "", ""],
    [291, 82, "Prisión de seis meses a tres años.", "false", "", ""],
    [292, 82, "Destitución del empleo.", "false", "", ""],
    [293, 83, "Seis meses a dos años.", "false", "", ""],
    [294, 83, "Dos a seis años.", "false", "", ""],
    [295, 83, "Uno a dos años.", "true", "", ""],
    [296, 83, "Tres a seis meses.", "false", "", ""],
    [297, 84, "Prisión de tres a seis años.", "false", "", ""],
    [298, 84, "Prisión de cuatro a diez años.", "true", "", ""],
    [299, 84, "Destitución del empleo y arresto.", "false", "", ""],
    [300, 84, "Prisión de diez a veinte años.", "false", "", ""],
    [301, 85, "Se niega a portar la Bandera Nacional en un desfile.", "false", "", ""],
    [302, 85, "No saluda correctamente el Lábaro Patrio durante una ceremonia.", "false", "", ""],
    [303, 85, "Maltrate la Bandera o Escudo de la Nación, o les falte al respeto o consideración debidos.", "true", "", ""],
    [304, 85, "No canta el Himno Nacional completo en actos oficiales.", "false", "", ""],
    [305, 86, "Destitución de empleo y prisión de uno a cinco años.", "false", "", ""],
    [306, 86, "Prisión de uno a cuatro años.", "true", "", ""],
    [307, 86, "Arresto y multa.", "false", "", ""],
    [308, 86, "Prisión de seis meses a dos años.", "false", "", ""],
    [309, 87, "Permite la entrada a una persona sin identificarla correctamente.", "false", "", ""],
    [310, 87, "No reporta un incidente ocurrido durante su turno.", "false", "", ""],
    [311, 87, "Abandone su puesto sin haber sido legítimamente relevado.", "true", "", ""],
    [312, 87, "Se queda dormido por menos de diez minutos en su puesto.", "false", "", ""],
    [313, 88, "Prisión de uno a seis meses.", "false", "", ""],
    [314, 88, "Prisión de dos meses a un año.", "true", "", ""],
    [315, 88, "Arresto mayor.", "false", "", ""],
    [316, 88, "Prisión de tres meses a dos años.", "false", "", ""],
    [317, 89, "Prisión de cinco a diez años.", "false", "", ""],
    [318, 89, "Prisión de seis a quince años.", "true", "", ""],
    [319, 89, "Destitución del empleo y prisión de tres años.", "false", "", ""],
    [320, 89, "La misma pena que la deserción en tiempo de guerra.", "false", "", ""],
    [321, 90, "Abandone su puesto sin haber sido legítimamente relevado.", "true", "", ""],
    [322, 90, "Permite que sus elementos duerman durante el servicio.", "false", "", ""],
    [323, 90, "No instruye correctamente a sus elementos antes de la guardia.", "false", "", ""],
    [324, 90, "Excede el tiempo asignado para su servicio.", "false", "", ""],
    [325, 91, "Porta un uniforme fuera de las horas de servicio.", "false", "", ""],
    [326, 91, "Usa una condecoración sin haberla limpiado.", "false", "", ""],
    [327, 91, "Use uniformes, divisas, o condecoraciones que no le corresponden, o que hubiere dejado de usar legalmente.", "true", "", ""],
    [328, 91, "Vende un uniforme militar en el mercado.", "false", "", ""],
    [329, 92, "Prisión de tres meses a un año.", "false", "", ""],
    [330, 92, "Destitución del empleo.", "false", "", ""],
    [331, 92, "Prisión de un mes a un año.", "true", "", ""],
    [332, 92, "Arresto y multa.", "false", "", ""],
    [333, 93, "Oculte, mutile, destruya o altere, sin derecho, documentos u objetos concernientes al servicio militar.", "true", "", ""],
    [334, 93, "Pierde su credencial de identificación militar por descuido.", "false", "", ""],
    [335, 93, "Extravía un manual de procedimientos militares.", "false", "", ""],
    [336, 93, "No entrega un informe a tiempo.", "false", "", ""],
    [337, 94, "Prisión de seis meses a dos años.", "false", "", ""],
    [338, 94, "Prisión de uno a seis años.", "true", "", ""],
    [339, 94, "Destitución y prisión de tres meses a un año.", "false", "", ""],
    [340, 94, "Prisión de tres a cinco años.", "false", "", ""],
    [341, 95, "Falte en el cumplimiento de cualquiera de los deberes generales de que habla el Artículo 159 de la Ley Orgánica del Ejército y Armada Nacionales, o el 27 de la Ley de Ascensos y Recompensas.", "true", "", ""],
    [342, 95, "Abandona su puesto de centinela sin ser relevado.", "false", "", ""],
    [343, 95, "Se insubordina verbalmente a un superior jerárquico.", "false", "", ""],
    [344, 95, "Se separa de su unidad por más de 72 horas sin permiso.", "false", "", ""],
    [345, 96, "Prisión de seis meses a dos años.", "false", "", ""],
    [346, 96, "Destitución del empleo y arresto.", "false", "", ""],
    [347, 96, "Prisión de tres a seis años.", "true", "", ""],
    [348, 96, "Prisión de diez a veinte años.", "false", "", ""],
    [349, 97, "Incurra en alguna de las faltas que el Reglamento o la Ordenanza señalan como infracción de deberes de centinela o vigilante.", "true", "", ""],
    [350, 97, "Se queda dormido en su puesto por más de una hora.", "false", "", ""],
    [351, 97, "Pierde su arma de cargo por negligencia.", "false", "", ""],
    [352, 97, "Permite la entrada al cuartel sin solicitar identificación.", "false", "", ""],
    [353, 98, "Prisión de seis meses a dos años.", "false", "", ""],
    [354, 98, "Prisión de un mes a un año.", "true", "", ""],
    [355, 98, "Arresto mayor.", "false", "", ""],
    [356, 98, "Prisión de tres meses a dos años.", "false", "", ""],
    [357, 99, "Prisión de seis meses a un año.", "false", "", ""],
    [358, 99, "Prisión de uno a cuatro años.", "true", "", ""],
    [359, 99, "Prisión de cuatro a diez años.", "false", "", ""],
    [360, 99, "Prisión de diez a veinte años.", "false", "", ""],
    [361, 100, "Falte en el cumplimiento de los deberes especiales de su comisión o empleo, o cometa actos que lo deshonren.", "true", "", ""],
    [362, 100, "Se ausenta de su domicilio por más de 72 horas sin notificar.", "false", "", ""],
    [363, 100, "Es grosero con un superior jerárquico en la calle.", "false", "", ""],
    [364, 100, "Finge enfermedad para evitar un servicio de guardia.", "false", "", ""],
    [365, 101, "Arresto de tres días y multa.", "false", "", ""],
    [366, 101, "Prisión de tres meses a dos años.", "false", "", ""],
    [367, 101, "Prisión de dos meses a dos años.", "true", "", ""],
    [368, 101, "Destitución del empleo.", "false", "", ""],
    [369, 102, "La falta causa perjuicio a tercero o al servicio público.", "true", "", ""],
    [370, 102, "El militar es de jerarquía elevada.", "false", "", ""],
    [371, 102, "El militar es reincidente en el delito.", "false", "", ""],
    [372, 102, "La falta ocurre en un acto social.", "false", "", ""],
    [373, 103, "Se niega a cumplir una orden por razones personales.", "false", "", ""],
    [374, 103, "Abandona su cargo en medio de un ejercicio.", "false", "", ""],
    [375, 103, "Cometa actos de inmoralidad o se halle en estado de embriaguez o bajo la influencia de narcóticos o enervantes, dentro de los recintos militares, o fuera de ellos portando uniforme.", "true", "", ""],
    [376, 103, "Pierde su credencial de identificación por descuido.", "false", "", ""],
    [377, 104, "Arresto de 15 a 45 días.", "false", "", ""],
    [378, 104, "Prisión de un mes a un año.", "true", "", ""],
    [379, 104, "Prisión de seis meses a dos años.", "false", "", ""],
    [380, 104, "Destitución del empleo.", "false", "", ""],
    [381, 105, "Arresto hasta que cumpla con su obligación.", "false", "", ""],
    [382, 105, "Prisión de un mes a un año.", "true", "", ""],
    [383, 105, "Destitución de empleo.", "false", "", ""],
    [384, 105, "Multa equivalente al doble de los alimentos adeudados.", "false", "", ""],
]

# Escribir el archivo CSV
output_file = '/home/devilegox/Documentos/FIBRA/FIBRA/streamlit/challenge_options_leccion2.csv'
with open(output_file, 'w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(options_data)

print(f"Archivo creado exitosamente: {output_file}")
print(f"Total de filas: {len(options_data)}")
